import type {
  AnalysisSummaryResponse,
  ArchitectureResponse,
  ChatResponse,
  FindingsResponse,
  RoadmapResponse,
} from "../types";

export const demoAnalysis: AnalysisSummaryResponse = {
  analysis_id: "analysis_demo_repo",
  status: "completed",
  stage: "complete",
  repository: {
    name: "atlas-workbench",
    source_type: "github",
    url: "https://github.com/reporevive/atlas-workbench",
  },
  stack: {
    frontend: ["React", "Vite", "TypeScript"],
    backend: ["FastAPI", "Python"],
    database: ["PostgreSQL"],
    testing: ["Vitest"] ,
  },
  summary: {
    files_analyzed: 86,
    analysis_duration_ms: 6840,
    findings_by_severity: { critical: 0, high: 2, medium: 4, low: 3, info: 0 },
    readiness_label: "needs_attention",
  },
  created_at: "2026-08-24T06:30:00Z",
  completed_at: "2026-08-24T06:30:07Z",
};

export const demoArchitecture: ArchitectureResponse = {
  components: [
    { id: "frontend", type: "frontend", label: "React + Vite", evidence_files: ["frontend/package.json", "frontend/vite.config.ts"] },
    { id: "backend", type: "backend", label: "FastAPI + Python", evidence_files: ["backend/app/main.py", "backend/requirements.txt"] },
    { id: "persistence", type: "persistence", label: "PostgreSQL", evidence_files: ["backend/app/db/session.py", "backend/.env.example"] },
    { id: "deployment", type: "deployment", label: "Render service", evidence_files: ["render.yaml"] },
  ],
  connections: [
    { source: "frontend", target: "backend", label: "HTTP API", evidence_files: ["frontend/src/api/client.ts"] },
    { source: "backend", target: "persistence", label: "SQLAlchemy connection", evidence_files: ["backend/app/db/session.py"] },
    { source: "deployment", target: "backend", label: "Hosts service", evidence_files: ["render.yaml"] },
  ],
};

export const demoFindings: FindingsResponse = {
  total: 9,
  items: [
    {
      id: "finding_001",
      severity: "high",
      category: "api_mismatch",
      title: "Frontend request has no matching backend route",
      description: "A frontend request references a route that was not found in the supported backend route map.",
      file: "frontend/src/features/search/searchApi.ts",
      line: 24,
      evidence: "POST /api/jobs/search",
      confidence: 0.91,
      recommendation: "Implement the matching backend route or update the frontend API contract before releasing the search flow.",
      verification_status: "evidence_backed",
    },
    {
      id: "finding_002",
      severity: "high",
      category: "security",
      title: "Potential credential pattern in local configuration",
      description: "A value matches a recognizable credential pattern. RepoRevive masked the value before presenting or transmitting evidence.",
      file: "backend/.env.local",
      line: 7,
      evidence: "OPENAI_API_KEY=••••••••••••••••",
      confidence: 0.88,
      recommendation: "Rotate the exposed value, remove the file from version control, and keep only a placeholder in .env.example.",
      verification_status: "evidence_backed",
    },
    {
      id: "finding_003",
      severity: "medium",
      category: "configuration",
      title: "Environment template omits a referenced variable",
      description: "The backend reads DATABASE_URL, but the repository template does not document the variable for a new setup.",
      file: "backend/app/settings.py",
      line: 18,
      evidence: "settings.database_url ← DATABASE_URL",
      confidence: 0.86,
      recommendation: "Add DATABASE_URL to backend/.env.example and document the expected local PostgreSQL setup.",
      verification_status: "evidence_backed",
    },
    {
      id: "finding_004",
      severity: "medium",
      category: "testing",
      title: "No recognizable backend test suite detected",
      description: "The repository includes frontend tests but no supported backend test directory or pytest files were found.",
      file: "backend/",
      evidence: "0 pytest files found",
      confidence: 0.84,
      recommendation: "Add focused pytest coverage for route behavior, settings validation, and database error handling.",
      verification_status: "evidence_backed",
    },
    {
      id: "finding_005",
      severity: "medium",
      category: "documentation",
      title: "Setup instructions stop before database initialization",
      description: "The README explains how to start the frontend but does not document the migration or seed step required by the backend.",
      file: "README.md",
      line: 42,
      evidence: "npm run dev",
      confidence: 0.78,
      recommendation: "Add a complete local setup path covering environment variables, migrations, seed data, and both service commands.",
      verification_status: "evidence_backed",
    },
    {
      id: "finding_006",
      severity: "medium",
      category: "deployment",
      title: "Deployment config does not declare a health check",
      description: "The deployment manifest starts the backend but does not include a health check path for readiness monitoring.",
      file: "render.yaml",
      line: 16,
      evidence: "healthCheckPath: missing",
      confidence: 0.73,
      recommendation: "Point the hosting health check at /health and verify the service returns a useful readiness response.",
      verification_status: "evidence_backed",
    },
    {
      id: "finding_007",
      severity: "low",
      category: "dependency",
      title: "Package manager lockfile is not present",
      description: "A package manifest was detected without its expected lockfile, which can make deployments less reproducible.",
      file: "frontend/package.json",
      confidence: 0.69,
      evidence: "package-lock.json: not found",
      recommendation: "Commit the lockfile generated by the chosen package manager and use frozen installs in CI.",
      verification_status: "evidence_backed",
    },
    {
      id: "finding_008",
      severity: "low",
      category: "documentation",
      title: "Repository purpose is not stated in the README opening",
      description: "The README begins with installation commands and does not provide a concise project overview for a new maintainer.",
      file: "README.md",
      line: 1,
      confidence: 0.66,
      evidence: "Heading: Setup",
      recommendation: "Add a one-paragraph overview, target user, and architecture sketch before setup instructions.",
      verification_status: "evidence_backed",
    },
    {
      id: "finding_009",
      severity: "low",
      category: "testing",
      title: "No CI test command is configured",
      description: "The repository has a Vitest dependency but no workflow was found that runs the test suite on pull requests.",
      file: ".github/workflows/",
      confidence: 0.63,
      evidence: "test workflow: not found",
      recommendation: "Add a lightweight CI workflow that installs dependencies, runs tests, and builds the frontend.",
      verification_status: "evidence_backed",
    },
  ],
};

export const demoRoadmap: RoadmapResponse = {
  items: [
    { id: "task_001", priority: "high", title: "Resolve the missing search route", description: "Align the frontend request with an implemented backend route so the core search flow has a verified contract.", related_finding_ids: ["finding_001"], related_files: ["frontend/src/features/search/searchApi.ts", "backend/app/main.py"], estimated_complexity: "medium" },
    { id: "task_002", priority: "high", title: "Rotate and remove the credential pattern", description: "Rotate the masked value, remove the local environment file from version control, and verify ignore rules.", related_finding_ids: ["finding_002"], related_files: ["backend/.env.local", ".gitignore"], estimated_complexity: "small" },
    { id: "task_003", priority: "medium", title: "Make a clean setup reproducible", description: "Document DATABASE_URL, migrations, and the complete two-service startup flow for a new contributor.", related_finding_ids: ["finding_003", "finding_005", "finding_007"], related_files: ["backend/.env.example", "README.md", "frontend/package.json"], estimated_complexity: "medium" },
    { id: "task_004", priority: "medium", title: "Add backend coverage and CI", description: "Cover the highest-risk backend paths and run the suite on every pull request before deployment.", related_finding_ids: ["finding_004", "finding_009"], related_files: ["backend/tests/", ".github/workflows/ci.yml"], estimated_complexity: "large" },
    { id: "task_005", priority: "low", title: "Improve deployment observability", description: "Configure the hosting health check and add a concise project architecture section to the README.", related_finding_ids: ["finding_006", "finding_008"], related_files: ["render.yaml", "README.md"], estimated_complexity: "small" },
  ],
};

export const demoChat: ChatResponse = {
  answer: "The job search flow appears incomplete because the inspected frontend sends POST /api/jobs/search, but that path was not present in the supported backend route map. The repository also lacks backend tests that would have caught the contract gap before release.",
  citations: [
    { file: "frontend/src/features/search/searchApi.ts", line: 24, excerpt: "client.post('/api/jobs/search', payload)" },
    { file: "backend/app/main.py", line: 38, excerpt: "registered routes: /health, /api/jobs" },
  ],
  confidence: 0.89,
  insufficient_evidence: false,
};
